### ISSUE TITLE
Show Slidr on larger screens and make it a slider on mobile?

### ISSUE THREAD

**Issue by IngwiePhoenix** [artberri/sidr#232]
Hey.

I actually like side-panel menus and would like to have one that would stay permanently visible on a desktop, but would gladly fold away on a mobile device / smaller viewport. Is this possible with slidr?

Kind regards Ingwie.

**Comment by peucaio** [comment]
Hi Ingwie,
I was having the same issue, and solved by using media queries to control the display of Sidr.
Please adapt for your use.

```css
/* for mobile */
@media screen and (max-width: 48.24em) {
	/*sidr menu*/
	.sidr {
		display: none;
		position: absolute;
		position: fixed;
		top: 0px;
		height: 100%;
		z-index: 99999;
		width: 260px;
		overflow-x: none;
		overflow-y: auto;
	}
	.sidr.right {
		left: auto;
		right: -260px
	}
	.sidr.left {
		left: -260px;
		right: auto
	}
}

/* from tablets up, reset sidr */

@media screen and (min-width: 48.25em) {
	.sidr {
		display: block;
		position: inherit;
		top: inherit;
		height: inherit;
		width: inherit; }
	.sidr.right {
		left: inherit;
		right: inherit; }
	.sidr.left {
		left: inherit;
		right: inherit; }
	body {
		width: 100% !important;
		left: inherit !important;
		right: inherit !important;
		position: inherit !important; }
}
```

Hope it helps.
