### ISSUE TITLE
Much smoother scrolling in panels

### ISSUE THREAD

**Issue by phoenixMag00** [artberri/sidr#40]
Hey. First of all, thank you so much for creating this plugin. It's fantastic. However, I was having some issues with scrolling within the slide panel. It felt like the menu was getting stuck when scrolling. The "stickiness" was causing me to accidentally click on the links in the sidebar.

However, I was able to get the scrolling smoothed out by changing:

```css
 .sidr {
    display: none;
    position: absolute;
    position: fixed;
    top: 0;
    height: 100%;
    z-index: 999999;
    width: 200px;
    overflow-x: none;
    overflow-y: auto;
    font-family: "lucida grande",tahoma,verdana,arial,sans-serif;
    font-size: 15px;
    background: #333;
    color: #fff;
    -webkit-box-shadow: inset 0 0 5px 5px #222;
    -moz-box-shadow: inset 0 0 5px 5px #222;
    box-shadow: inset 0 0 5px 5px #222;
}
```
to:

```css
 .sidr {
    display: none;
    position: absolute;
    position: fixed;
    top: 0;
    height: 100%;
    z-index: 999999;
    width: 200px;
    overflow-x: none;
    overflow-y: auto;
    font-family: "lucida grande",tahoma,verdana,arial,sans-serif;
    font-size: 15px;
    background: #333;
    color: #fff;
    -webkit-box-shadow: inset 0 0 5px 5px #222;
    -moz-box-shadow: inset 0 0 5px 5px #222;
    box-shadow: inset 0 0 5px 5px #222;
    -webkit-overflow-scrolling: touch;
}
```

and then adding:

```css
.sidr > * {-webkit-transform: translateZ(0px);}
```
right below .sidr

This helps out in iOS 5 and above. Not too sure about Android. Trying to find a testing device to confirm.
