### ISSUE TITLE
Transparent menu in iOS 7.0.3

### ISSUE THREAD

**Issue by kjprince** [artberri/sidr#95]
Hey I've tested this in IE9+, Chrome, Android, FF and it seems to work well....

But on iOS the fly-out menu is transparent....The links still work but the menu just shows the body background. 

You can see it here: http://www.castakite.com

Here's my HTML:

``` html
<div id="mobile-nav">
  <a id="mobile-logo" class="hide-text fl" title="Castakite Kite Flying Handle" href="/">Castakite Kite Flying Handle</a>
  <a id="responsive-menu-button" href="#sidr-main" class="fr menu-button">Menu</a>

  <div id="mobile-nav-flyout" style="display: none;">
    <ul>
      <li>
        <a class="nav-link" href="/">Home</a>
      </li>

      <li>
        <a class="nav-link" href="/pages/about">About</a>
      </li>

      <li>
        <a class="nav-link" href="/pages/contact">Contact</a>
      </li>

      <li>
        <a class="nav-link" href="/account/login">Login</a>
      </li>

      <li>
        <a class="nav-link" href="/pages/faq">FAQ</a>
      </li>
    </ul>  
  </div>
</div>
```

And my CSS:

``` css
#mobile-nav {
  width: 100%;
  position: fixed;
  top: 0;
  background: #fff;
  max-height: 55px;
  height: 55px;
  z-index: 201;
  -webkit-box-shadow: rgba(0, 0, 0, 0.1) 0 2px;
  -moz-box-shadow: rgba(0, 0, 0, 0.1) 0 2px;
  box-shadow: rgba(0, 0, 0, 0.1) 0 2px;
  display: block;
}

#mobile-nav-flyout {
  z-index: 999;
}

#responsive-menu-button {
  margin-right: 1em;
  margin-top: .35em;
  height: 40px;
  width: 80px;
  -webkit-border-radius: 0.25em;
  -moz-border-radius: 0.25em;
  border-radius: 0.25em;
  color: #FFFFFF;

}

.menu-button {
line-height: 20px;
text-align: left;
padding: 10px;
font-weight: 600;
background: #146FA3;

}

#responsive-menu-button:after {
  background: url('');
  background-size: ;
  height:;
  width:;
}

#mobile-logo {
  background: url('http://cdn.shopify.com/s/files/1/0251/4105/files/castakite-mobile-logo.png?15233');
  background-repeat: no-repeat;
  margin-top: 5px;
  margin-bottom: 5px;
  margin-left: 1em;
  height: 44px;
  width: 105px;
}

nav {
  display: none;
}
```
